import Head from "next/head";

const Register = () => {
    return (  
        <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        hello world | register
      </main>
    </>
    );
}
 
export default Register;