import Head from "next/head";

const Contact = () => {
    return (  
        <>
      <Head>
        <title>contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        hello world | contact
      </main>
    </>
    );
}
 
export default Contact;