import { ContactStyles } from "@/styles/PageStyles/Contact";
import Head from "next/head";

const Contact = () => {
    return (  
        <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ContactStyles>
          contact us
        </ContactStyles>
      </main>
    </>
    );
}
 
export default Contact;