import { FB, IG, LinkedIn, XIcon } from "@/components/Icons/Icons";
import { LargeBtnStyle } from "@/styles/ComponentStyles/Buttons";
import {
  ErrorStyles,
  NormalTextStyles,
  SmallTextStyles,
} from "@/styles/ComponentStyles/Text";
import { ContactStyles } from "@/styles/PageStyles/Contact";
import Head from "next/head";
import Link from "next/link";
import { useForm } from "react-hook-form";
import { useEffect, useState } from "react";
import { AnimatePresence } from "framer-motion";
import { ContacSuccess } from "@/components/Contact/Contact";
import { ButtonLoader } from "@/styles/PageStyles/auth/Register";

interface IForm {
  firstName: string;
  email: string;
  message: string;
}

const Contact = () => {
  const {
    register,
    reset,
    setValue,
    handleSubmit,
    formState: { errors },
  } = useForm<IForm>({
    mode: "onBlur",
    defaultValues: {
      firstName: "",
      email: "",
      message: "",
    },
  });
  const [isLoading, setLoading] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);
  const cancel = () => {
    setIsSuccess(false);
  };
  const sendMessage = () => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      reset();
      setIsSuccess(true);
    }, 2000);
  };
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AnimatePresence>
          {isSuccess && <ContacSuccess handleClose={cancel} key="kagura" />}
        </AnimatePresence>
        <ContactStyles>
          <div className="one">
            <div className="one-a">
              <h3>Get in touch</h3>
              <NormalTextStyles>
                Contact <br /> Information
              </NormalTextStyles>
              <NormalTextStyles>
                27,Alara Street <br /> Yaba 100012 <br /> Lagos State
              </NormalTextStyles>
              <NormalTextStyles>Call Us : 07067981819</NormalTextStyles>
              <NormalTextStyles>
                we are open from Monday-Friday <br />
                08:00am - 05:00pm
              </NormalTextStyles>
            </div>
            <div className="one-b">
              <NormalTextStyles>Share on</NormalTextStyles>
              <div className="socials">
                <Link href="#">
                  <IG />
                </Link>
                <Link href="#">
                  <XIcon />
                </Link>
                <Link href="#">
                  <FB />
                </Link>
                <Link href="#">
                  <LinkedIn />
                </Link>
              </div>
            </div>
          </div>
          <div className="two">
            <form onSubmit={handleSubmit(sendMessage)}>
              <div className="h">
                <h3>Questions or need assistance?</h3>
                <h3>Let us know about it!</h3>
              </div>
              <SmallTextStyles className="mobile">
                Email us below to any question related to our event
              </SmallTextStyles>
              <div className="inner">
                <div className="fname">
                  <input
                    type="text"
                    {...register("firstName", { required: "Name is required" })}
                    id=""
                    placeholder="First Name"
                  />
                  {errors?.firstName && (
                    <ErrorStyles className="down">
                      {" "}
                      {errors.firstName.message}
                    </ErrorStyles>
                  )}
                </div>
                <div className="email">
                  <input
                    type="email"
                    {...register("email", { required: "Email is required" })}
                    id=""
                    placeholder="Email"
                  />
                  {errors?.firstName && (
                    <ErrorStyles className="down">
                      {" "}
                      {errors.firstName.message}
                    </ErrorStyles>
                  )}
                </div>
                <div className="message">
                  <textarea
                    id=""
                    rows={4}
                    {...register("message", {
                      required: "Message is required",
                    })}
                    placeholder="Message"
                  ></textarea>
                  {errors?.message && (
                    <ErrorStyles className="down">
                      {" "}
                      {errors.message.message}
                    </ErrorStyles>
                  )}
                </div>
              </div>
              <div className="btn">
                <LargeBtnStyle>{isLoading ? <ButtonLoader /> : "Submit"}</LargeBtnStyle>
              </div>
            </form>
            <div className="mobile">
              <div className="one-b">
                <NormalTextStyles>Share on</NormalTextStyles>
                <div className="socials">
                  <Link href="#">
                    <IG />
                  </Link>
                  <Link href="#">
                    <XIcon />
                  </Link>
                  <Link href="#">
                    <FB />
                  </Link>
                  <Link href="#">
                    <LinkedIn />
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </ContactStyles>
      </main>
    </>
  );
};

export default Contact;
